Quiz report (Teacher)
peiyuans-pals/toohakai pull request #40
Opened 2023-09-21 16:49 UTC by iAlanx3

2023-09-22 02:58 UTC, Zenteh-NTU requested changes

2023-09-22 02:58 UTC, Zenteh-NTU commented on apps/web/src/app/dashboard/teacher/quiz-reports/_components/Cards.tsx
> +*/
Remove this

2023-09-22 02:58 UTC, Zenteh-NTU commented on apps/web/src/app/dashboard/teacher/quiz-reports/[slug]/_components/StudentDropDownBar.tsx
> + */
Remove this

2023-09-23 09:14 UTC, iAlanx3 commented on apps/web/src/app/dashboard/teacher/quiz-reports/_components/Cards.tsx
> +*/
Removed

2023-09-23 09:14 UTC, iAlanx3 commented on apps/web/src/app/dashboard/teacher/quiz-reports/[slug]/_components/StudentDropDownBar.tsx
> + */
Removed

2023-09-25 00:14 UTC, Zenteh-NTU approved these changes

2023-09-25 00:14 UTC, merged